package com.github.group2.backend.entity;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "movies")
@NoArgsConstructor
@Data
public class Movie {
    @Id
    private String id;
    private String title;
    private String genre;

    // Field ID is autogenerated
    public Movie(String title, String genre) {
        this.title = title;
        this.genre = genre;
    }

    public Movie(String id, String title, String genre) {
        this.id = id;
        this.title = title;
        this.genre = genre;
    }
}
